---
kind: pipeline
type: docker
name: Linux amd64 test
platform:
  os: linux
  ar—Åh: amd64

steps:
  - name: Test in debug mode
    image: rust:buster
    commands:
      - apt-get update
      - apt-get -y install --no-install-recommends build-essential python cmake libvulkan-dev vulkan-utils
      - cargo test
  - name: Test in release mode
    image: rust:buster
    commands:
      - apt-get update
      - apt-get -y install --no-install-recommends build-essential python cmake libvulkan-dev vulkan-utils
      - cargo test --release
  - name: Discord report
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      avatar_url: https://www.sos-dan.ru/files/pedia/analysis/season_two/02/ee1_04.jpg
