---
kind: pipeline
type: docker
name: Linux amd64 test
platform:
  os: linux
  ar—Åh: amd64

steps:
  - name: Test in debug mode
    image: rust
    commands:
      - cargo test
  - name: Test in release mode
    image: rust
    commands:
      - cargo test --release
  - name: Discord report
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      avatar_url: https://www.vippng.com/png/detail/31-319881_smug-haruhi-haruhi-suzumiya-png.png
