[workspace]
members = [
    "core",
    "main_loop",
    "legion_ecs",
    "rapier_physics_3d",
    "engine",
    "asset_storage",
    "assets",
    "vulkano_graphics",
]

[profile.dev.package.rapier3d]
opt-level = 3

[profile.release]
codegen-units = 1
