[package]
name = "spc_clockwork_kernel"
version = "0.1.0"
authors = ["Yaroslav V. Petrov <yaroslav.v.petrov@yandex.ru>"]
edition = "2018"

[dependencies]
log = "0.4.14"
itertools = "0.10.0"
no_deadlocks = "1.2.0"
derive_builder = "0.10.2"
getset = "0.1.1"
ambassador = "0.2.1"
